---
title: "SET/MH QC plots"
date: "`r Sys.Date()`"
output: html_document
---


### Setup; data import and formatting

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r importAndFormat}
# open up important libraries
library(tidyverse)
library(lubridate)
library(knitr)


### pins
# read in; wide format
sets_wide <- read.csv("sets_wide_UPDATED.csv") %>%
    mutate(date = mdy(date)) 
# gather, so it's one row per pin. group by SET, date, arm.
sets_long <- sets_wide %>%
    gather(key="pin", value="value", -SET, -date, -arm) %>%
    group_by(SET, date, arm)
# create a summary dataset from sets_long, which is already grouped by SET-date-arm
sets_summByArm <- sets_long %>%
    summarize(meanPinHt = mean(value, na.rm=TRUE),
              sdPinHt = sd(value, na.rm=TRUE),
              sePinHt = sdPinHt/(length(value)))


### markers    
# read in; wide format
markers_wide <- read.csv("markers_UPDATED.csv") %>%
    mutate(date = mdy(date), ref_date = mdy(ref_date))
# gather; one row per reading
markers_long <- markers_wide %>%
    gather(key="reading", value="value", -SET, -MHplot, -date, -ref_date) %>%
    group_by(SET, MHplot, date) %>%
    arrange(SET, MHplot, date, reading)

```

****

### A peek at all the data tables that we're working with


#### SETs

```{r pindfHeads}

kable(head(sets_wide, 3), caption = "Pin readings - wide format")
kable(head(sets_long, 3), caption = "Pin readings - long format")
kable(head(sets_summByArm, 3), caption = "Pin readings - summary by arm position")

```


#### Marker Horizons

```{r markerdfHeads}

kable(head(markers_wide, 3), caption = "MH readings - wide format")
kable(head(markers_long, 3), caption = "MH readings - long format")

```

****
****


## Graphs galore



### SET readings


#### individual pins

```{r setGraphsByPin, fig.width=12, fig.height=30}

# plot in a grid: one column for each arm position (n=4), one row per SET (n=15).
# scales = "free" means the y-axis can vary in each panel; this will provide optimal scale within a panel but prevents meaningful comparisons between panels.
ggplot(sets_long, aes(x=date, y=value)) +
    geom_point(aes(col=pin), size=2, alpha=0.6) +
    facet_grid(SET ~ arm, scales="free") +
    ggtitle("Individual pin readings \neach column is an arm position; each row is a SET") +
    theme_bw()

```

```{r setGraphsByPinLong, fig.width=9, fig.height=80}
ggplot(sets_long, aes(x=date, y=value)) +
    geom_point(aes(col=pin), size=2, alpha=0.7) +
    facet_grid(SET + arm ~ ., scales="free") +
    ggtitle("Individual pin readings \neach row is one SET-arm position combination") +
    theme_bw()

# same graph, but with smaller, lighter points and include lines connecting each pin
ggplot(sets_long, aes(x=date, y=value)) +
    geom_point(aes(col=pin), size=2, alpha=0.5) +
    geom_line(aes(col=pin), alpha=0.8, lty=2) +
    facet_grid(SET + arm ~ ., scales="free") +
    ggtitle("Individual pin readings \neach row is one SET-arm position combination") +
    theme_bw()

```


#### arm position

```{r setGraphsBySET, fig.width=9, fig.height=20}

ggplot(sets_summByArm, aes(x=date, y=meanPinHt)) +
    geom_point(aes(col=arm), size=2.5, alpha=0.6) +
    geom_errorbar(aes(ymin = meanPinHt - sdPinHt, ymax = meanPinHt + sdPinHt, col=arm), show.legend=FALSE, alpha=0.6) +
    facet_grid(SET~., scales = "free") +
    ggtitle("Mean pin heights by arm \n+/- one standard deviation \neach row is one SET") +
    theme_bw()


# same graph, but smaller points and line connecting each arm
ggplot(sets_summByArm, aes(x=date, y=meanPinHt)) +
    geom_point(aes(col=arm), size=2, alpha=0.6) +
    geom_line(aes(col=arm), lty=2, alpha=0.8) +
    geom_errorbar(aes(ymin = meanPinHt - sdPinHt, ymax = meanPinHt + sdPinHt, col=arm), show.legend=FALSE, alpha=0.6) +
    facet_grid(SET~., scales = "free") +
    ggtitle("Mean pin heights by arm \n+/- one standard deviation \neach row is one SET") +
    theme_bw()

```

****

### Marker Horizons

#### by individual measurement
##### up to 4 per core

```{r MHgraphsByCoreGrid, fig.width=14, fig.height=25}

# colored by date of feldspar application
ggplot(markers_long, aes(x=date, y=value)) +
    geom_point(aes(col=as.factor(ref_date)), size=2.5, alpha=0.7) +
    facet_grid(SET ~ MHplot, scales="free") +
    ggtitle("Marker Horizons by plot (columns) within each SET (rows) \neach color represents a different feldspar application date") +
    theme_bw()
```



```{r MHgraphByCoreStacked, fig.width=9, fig.height=65}

ggplot(markers_long, aes(x=date, y=value)) +
    geom_point(aes(col=as.factor(ref_date)), size=2.5, alpha=0.7) +
    facet_grid(SET + MHplot ~ ., scales="free") +
    ggtitle("Marker Horizons by plot \neach row is one SET-MHplot combination \neach color represents a different feldspar application date") +
    theme_bw()

```

